version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python admin.products.consumer.py'
    depends_on:
      - db

  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
#      - HOST:localhost
      - POSTGRES_DB=admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
#      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      - backend
